name: CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Stop Mysql
        run: sudo service mysql stop
      - uses: getong/mariadb-action@v1.1
        with:
          mysql database: 'crud'
          mysql root password: 'password'
          mysql user: 'user' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'password'
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Test
        env:
          DATABASE_URL: "root:password@tcp(localhost:3306)/crud?charset=utf8&parseTime=True&loc=Local"
        run: go test ./...
