name: CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
         MYSQL_USER: user
         MYSQL_PASSWORD: password
         MYSQL_DATABASE: test
         MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Test
        env:
          DATABASE_URL: "user:pasword@tcp(0.0.0.0:3306)/crud?charset=utf8&parseTime=True&loc=Local"
        run: go test ./...
